before_script:
  - sudo service mongodb start || true
  - cp config/config.example.js config/config.js
  - cp config/imager.example.js config/imager.js
services:
  - mongodb
language: node_js
node_js:
  - "0.10"
  - "0.8"
